"""financiadores: capital aportado/disponible, rendimiento acordado, observaciones

Revision ID: 27439c14ec73
Revises: 8d55ada9690d
Create Date: 2026-07-13 22:35:04.183383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27439c14ec73'
down_revision: Union[str, None] = '8d55ada9690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default solo para no romper filas existentes; se saca al final
    # porque la app siempre manda estos valores explícitamente.
    op.add_column(
        'financiadores',
        sa.Column('capital_aportado', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'financiadores',
        sa.Column('capital_disponible', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'financiadores',
        sa.Column('rendimiento_acordado', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'),
    )
    op.add_column('financiadores', sa.Column('observaciones', sa.Text(), nullable=True))

    op.alter_column('financiadores', 'capital_aportado', server_default=None)
    op.alter_column('financiadores', 'capital_disponible', server_default=None)
    op.alter_column('financiadores', 'rendimiento_acordado', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financiadores', 'observaciones')
    op.drop_column('financiadores', 'rendimiento_acordado')
    op.drop_column('financiadores', 'capital_disponible')
    op.drop_column('financiadores', 'capital_aportado')
    # ### end Alembic commands ###
