"""modelos iniciales: usuarios, clientes, prestamos, evaluaciones, financiadores, desembolsos

Revision ID: 3f6e0ebad916
Revises: 
Create Date: 2026-07-13 15:54:45.464105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6e0ebad916'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financiadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'ANALISTA', 'CLIENTE', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_dni'), 'clientes', ['dni'], unique=True)
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto_solicitado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('SOLICITADO', 'EN_EVALUACION', 'APROBADO', 'RECHAZADO', 'DESEMBOLSADO', name='estado_prestamo'), nullable=False),
    sa.Column('financiador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['financiador_id'], ['financiadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desembolsos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_desembolso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestamo_id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('analista_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('APROBADO', 'RECHAZADO', name='decision_evaluacion'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestamo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluaciones')
    op.drop_table('desembolsos')
    op.drop_table('prestamos')
    op.drop_index(op.f('ix_clientes_dni'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('financiadores')
    # ### end Alembic commands ###
    sa.Enum(name='decision_evaluacion').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='estado_prestamo').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='rol_usuario').drop(op.get_bind(), checkfirst=True)
